version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn src.main:create_app --host 0.0.0.0 --port 8000 --factory
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:///./inno_quiz.db
    depends_on:
      - migration

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: streamlit run src/streamlit/app.py
    env_file:
      - .env
    depends_on:
      - api

  migration:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: alembic upgrade head
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:///./inno_quiz.db

  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: pytest
    env_file:
      - .env
    profiles:
      - test

  lint:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: >
      sh -c "flake8 src tests alembic &&
             ruff check src tests alembic --fix &&
             ruff format src tests alembic &&
             mypy src tests --show-error-codes &&
             toml-sort pyproject.toml --in-place --all"
    env_file:
      - .env
    profiles:
      - lint