version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - "5432:5432"
    profiles:
      - test

  redis:
    image: redis:latest
    command: [ "redis-server", "--requirepass", "password" ]
    ports:
      - "6379:6379"
    profiles:
      - test

  api:
    build: .
    command: "uvicorn src.main:create_app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  worker:
    build: .
    command: "celery -A src.celery.app:app worker --loglevel INFO"
    env_file:
      - .env.compose
    depends_on:
      - redis
      - db

  beat:
    build: .
    command: "celery -A src.celery.app:app beat --loglevel INFO"
    env_file:
      - .env.compose
    depends_on:
      - redis
